version: '3.3'

services:
        jenkins:
            container_name: jenkins-dc
            image: jenkins/jenkins
            ports: 
                - 8020:8080
                - 50000:50000
            volumes:
                    - ./data:/var/jenkins_home
