version: '3.3'

services:
        db:
          image: mariadb
          volumes:
                  - ./db:/var/lib/mysql
          restart: always
          environment:
                  MYSQL_ROOT_PASSWORD: wordpressRoot_dbPass
                  MYSQL_DATABASE: wordpress
                  MYSQL_USER: wordpress
                  MYSQL_PASSWORD: wordpres_pass

        wordpress:
          links:
                  - db:mysql
          image: wordpress:latest
          ports: 
                  - 8090:80
          restart: always
          environment:
                  WORDPRESS_DB_HOST: db:3306
                  WORDPRESS_DB_USER: wordpress
                  WORDPRESS_DB_PASSWORD: wordpres_pass
                  WORDPRESS_DB_NAME: wordpress
          volumes:
                  - ./wp-content:/var/www/html/wp-content
                  - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        phpmyadmin:
          links:
                  - db:mysql
          image: phpmyadmin/phpmyadmin
          restart: always
          ports: 
                  - 8091:80
          environment:
                  PMA_HOST: db
                  MYSQL_ROOT_PASSWORD: wordpressRoot_dbPass
                
volumes:
        db_data: {}
